---
title: Analysis of exocomet spectra
format:
  html:
    code-fold: true
    page-layout: full
jupyter: python3
---


# Analysis of exocomet spectra

### Théo Vrignaud — March 17, 2026

***

This notebook provides interactive visualisations of Beta Pictoris spectra obtained on **April 29** and **September 10, 2025**, with the Hubble Space Telescope (STIS and COS; program #17790) and the HARPS spectrograph at the 3.6m ESO telescope in La Silla, Chile (program 115.282N).

Both observations reveal absorption signatures from transiting exocomet gaseous tails, detected in lines of metallic ions (Fe II, Ni II, ...) and volatile tracers (C I). This notebook is designed to help explore and visualise these signatures interactively.

We also provide detailed views of the exocomet model used to fit each observational dataset. The physical description of this model is presented in:

- Vrignaud & Lecavelier 2026 (A&A, 707, A60), focused on the transit distance of the exocomets;
- Vrignaud et al. (in prep., 2026), focused on the C/Fe ratio.

The python codes used to plot the data and compute the transmission model can be retrieved at https://github.com/TVrignaud/Exocomet_spectrum.

```{python}
import numpy as np
import Routines
```

***
# Overview of the spectral data

This section provides interactive views of the Beta Pictoris spectra collected on **April 29** and **September 10, 2025**. For each instrument (STIS, COS, and HARPS), both epochs are compared against archival observations taken at different epochs.

For STIS and HARPS, we overplot in black a reconstruction of the photospheric continuum, obtained by averaging all available spectra over spectral regions unaffected by cometary absorption, and interpolating the result using a cubic spline.

Note that the spectra are shown in Beta Pic rest frame (v = + 20.5 km/s; Brandeker+2011)

***

```{python}
# Retrieve data : 
#    + Observations of Beta Pic are stored in Data_Beta_Pic.npy
#    + The dictionnary is organised as follows: 
#       - spec_dic['spec_renorm'] contains the observed spectra, which are organised by instrument/date of observation/spectrum/order.
#       - spec_dic['reference'] contains estimates of the stellar continuum without absorption from exocomets. 


spec_dic = np.load('Data_Beta_Pic.npy', allow_pickle = True).item()


list_visits_STIS =  [
                    '1997-12-06',  '1997-12-19',  
                    #  '2001-08-26',  '2001-08-27',  '2002-05-21',  '2002-05-22',  
                     '2017-10-09',  '2018-01-10',  '2018-03-07',  '2018-10-29',  '2018-12-15',  
                    #  '2024-04-17',  '2024-07-31',  '2024-08-08',  
                     '2025-04-29',  '2025-09-03',  '2025-09-10',  '2025-10-13'
                     ]  


list_visits_COS  =  ['2014-02-22',  '2015-12-10',  '2016-01-30',  '2017-04-23', 
                     '2017-06-10',  '2017-08-04',  '2017-10-20',  '2017-11-26', 
                     '2018-03-17',  '2018-05-09',  '2018-10-29',  '2018-12-15', 
                     '2025-04-29',  '2025-09-03',  '2025-09-10',  '2025-10-13']


list_visits_HARPS = ['2024-04-17', '2024-08-08', '2025-04-29', '2025-09-03', '2025-09-10']

# Attribute color to each spectrum
colors = ['royalblue', 'firebrick', 'darkorange', 'seagreen', 'darkviolet', 'goldenrod', 'deeppink', 'teal', 'saddlebrown', 'mediumslateblue']
date_to_color = {}
for i, date in enumerate(sorted(set(list_visits_STIS) | set(list_visits_COS) | set(list_visits_HARPS))) : date_to_color[date] = colors[i%len(colors)]
```

### STIS

```{python}
# STIS spectra from 1997 to 2025
inst = 'STIS'
visits_plots = list_visits_STIS
visits_emphasis = ['2025-04-29', '2025-09-10']
plot_error_bar = False

fig = Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, 
                                      plot_reference = 'Photospheric continuum', 
                                      visits_emphasis = visits_emphasis, date_to_color = date_to_color, title = 'Beta Pic (HST/STIS)', 
                                      loc_label = 'upper right')
```

### COS

```{python}
# COS spectra from 2014 to 2025
inst = 'STIS'
inst = 'COS'
visits_plots = list_visits_COS
visits_emphasis = ['2025-04-29', '2025-09-10']
plot_error_bar = False

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = None, visits_emphasis = visits_emphasis, date_to_color = date_to_color, title = 'Beta Pic (HST/COS)')
```

### HARPS

```{python}
# HARPS spectra from 2024 - 2025
inst = 'HARPS'
visits_plots = list_visits_HARPS
visits_emphasis = ['2025-04-29', '2025-09-10']
plot_error_bar = False

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, 
                                plot_reference = 'Photospheric continuum', visits_emphasis = visits_emphasis, 
                                date_to_color = date_to_color, xlim = [3900,4000], title = 'Beta Pic (HST/HARPS)')
```

***

# Zoom on individual lines

Spectra obtained on April 19 and September 10, 2025 are shown around three Fe II, C I and Ca II lines

Both spectra exhibit sharp absorption components at low velocities:

- Three low-velocity comets at -7, +3 and + 10 km/s (respectively LVC 1, 2, 3) in the April 29 spectrum;
- Two low-velocity comets at +4 and + 13 km/s (respectively LVC 4, 5) in the September 10, 2025 spectrum. 

These five low-velocity comets (LVC) are studied in Vrignaud & Lecavelier 2026 (A&A, 707, A60) and Vrignaud et al. (in prep., 2026)

***

```{python}
# Fe II line at 2629 A
inst = 'STIS'
visits_plots = list_visits_STIS
visits_emphasis = ['2025-04-29', '2025-09-10']
plot_error_bar = False
line = 2629.0766

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Photospheric continuum', visits_emphasis = visits_emphasis, date_to_color = date_to_color, 
                    line = line, xlim = [-150,150], loc_label = 'lower right', title = 'Fe II - 2629 Å (HST/STIS)')
```

```{python}
# C I line at 1560.3 A
inst = 'STIS'
visits_plots = list_visits_STIS
visits_emphasis = ['2025-04-29', '2025-09-10']
plot_error_bar = False
line = 1560.31

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Photospheric continuum', visits_emphasis = visits_emphasis, date_to_color = date_to_color, 
                    line = line, xlim = [-150,150], title = 'C I - 1560 Å (HST/STIS)')
```

```{python}
# Ca II K line at 3933.66 A
inst = 'HARPS'
visits_plots = list_visits_HARPS
visits_emphasis = ['2025-04-29', '2025-09-10']
plot_error_bar = False
line = 3933.661

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Photospheric continuum', visits_emphasis = visits_emphasis, date_to_color = date_to_color, 
                    line = line, xlim = [-150,150], title = 'Ca II - 3933 Å (HARPS)', loc_label = 'lower right')
```

***

# Extracting exocomet spectra

For each epoch, a specific reference spectrum was built to isolate the absorption signatures of the five LVCs

- For STIS, the reference spectrum covers the whole 1500-2900 A range
- For COS, the reference spectrum targets only specific lines of C I, Ni II, S I and Si II. Other species are either strongly saturated or affected by geocoronal emission
- For HARPS, the reference spectrum covers the Ca II doublet only

***

# 2025-04-29 observations

***

### HST/STIS

```{python}
# View of the STIS spectrum taken on 2025-04-29
inst = 'STIS'
visits_plots = ['2025-04-29']
visits_emphasis = ['2025-04-29']
plot_error_bar = False

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-04-29 STIS', 
                                visits_emphasis = visits_emphasis, date_to_color = date_to_color, title = '2025-04-29 (HST/STIS)')
```

### HST/COS

```{python}
# View of the COS spectrum taken on 2025-04-29
inst = 'COS'
visits_plots = ['2025-04-29']
visits_emphasis = ['2025-04-29']
plot_error_bar = False

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-04-29 COS', visits_emphasis = visits_emphasis, date_to_color = date_to_color, title = '2025-04-29 (HST/COS)')
```

### HARPS

```{python}
# View of the HARPS spectrum taken on 2025-04-29
inst = 'HARPS'
visits_plots = ['2025-04-29']
visits_emphasis = ['2025-04-29']
plot_error_bar = False

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, 
                                plot_reference = 'Continuum 2025-04-29 HARPS', visits_emphasis = visits_emphasis, 
                                date_to_color = date_to_color, title = '2025-04-29 (HARPS)',
                                xlim = [3900,4000])
```

### Zoom on two Fe II and C I lines

The three LVCs (at -7, +3 and +10 km/s) are clearly distinguishable in the Fe II line. They are a bit more saturated in C I.

```{python}
# Zoomed-in view of the 2025-04-29 spectrum around the Fe II line at 2629 A (STIS)
inst = 'STIS'
visits_plots = ['2025-04-29']
visits_emphasis = ['2025-04-29']
plot_error_bar = False
line = 2629.0766

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-04-29 STIS', visits_emphasis = visits_emphasis, 
                    line = line, xlim = [-150,150], date_to_color = date_to_color, title = 'Fe II - 2629 Å (HST/STIS)')
```

```{python}
# Zoomed-in view of the 2025-04-29 spectrum around the C I line at 1560.3 A (STIS)
inst = 'STIS'
visits_plots = ['2025-04-29']
visits_emphasis = ['2025-04-29']
plot_error_bar = False
line = 1560.31

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-04-29 STIS', visits_emphasis = visits_emphasis, 
                    line = line, xlim = [-150,150], date_to_color = date_to_color, title = 'C I - 1560 Å (HST/STIS)')
```

*** 

# 2025-09-10 observations

***

### HST/STIS

```{python}
# View of the STIS spectrum taken on 2025-09-10
inst = 'STIS'
visits_plots = ['2025-09-10']
visits_emphasis = ['2025-09-10']
plot_error_bar = False

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-09-10 STIS', 
                                visits_emphasis = visits_emphasis, date_to_color = date_to_color, title = '2025-09-10 (HST/STIS)')


```

### HST/COS

```{python}
# View of the COS spectrum taken on 2025-09-10
inst = 'COS'
visits_plots = ['2025-09-10']
visits_emphasis = ['2025-09-10']
plot_error_bar = False

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-09-10 COS', visits_emphasis = visits_emphasis, date_to_color = date_to_color, title = '2025-09-10 (COS)')
```

### HARPS

```{python}
# View of the HARPS spectrum taken on 2025-09-10
inst = 'HARPS'
visits_plots = ['2025-09-10']
visits_emphasis = ['2025-09-10']
plot_error_bar = False

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-09-10 HARPS', 
                                visits_emphasis = visits_emphasis, date_to_color = date_to_color, title = '2025-09-10 (HARPS)',
                                xlim = [3900,4000])
```

### Zoom on two Fe II and C I lines

Again, the two LVCs (at + 4 and + 12 km/s) are clearly distinguishable in the Fe II line, and are slightly more saturated in C I

```{python}
# Zoomed-in view of the 2025-09-10 spectrum around the Fe II line at 2629 A (STIS)
inst = 'STIS'
visits_plots = ['2025-09-10']
visits_emphasis = ['2025-09-10']
plot_error_bar = False
line = 2629.0766

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-09-10 STIS', visits_emphasis = visits_emphasis, date_to_color = date_to_color, 
                    line = line, xlim = [-150,150], title = 'Fe II - 2629 Å (HST/STIS)')
```

```{python}
# Zoomed-in view of the 2025-09-10 spectrum around the C I line at 1560.3 A (STIS)
inst = 'STIS'
visits_plots = ['2025-09-10']
visits_emphasis = ['2025-09-10']
plot_error_bar = False
line = 1560.31

Routines.plot_observed_spectrum(spec_dic, inst, visits_plots, plot_error_bar = False, plot_reference = 'Continuum 2025-09-10 STIS', visits_emphasis = visits_emphasis, date_to_color = date_to_color, 
                    line = line, xlim = [-150,150], title = 'C I - 1560 Å (HST/STIS)')
```

***

# View of the fitted model

Spectra from each epoch were fitted using the model described in Vrignaud & Lecavelier 2026 (A&A, 707, A60) and Vrignaud et al. (in prep., 2026). In this model, each low-velocity exocomet (LVC) is described using few parameters:
- Its line profile (reconstructed using a PCHIP interpolation)
- Its distance to the star (which sets the efficiency of radiative excitation, and thus the excitation state of the gas)
- Its composition (one column density for each species; here we fitted Fe II, Ni II, Si II, Cr II, Mn II, Ca II, S I and C I lines)

For each epoch, several absorption components were modeled: 
- The LVCs (LVC 1, 2 and 3 for April 29 spectrum; LVC 4 and 5 for September 10 spectrum);
- The circumstellar disc (narrow feature at 0 km/s, detected mostly in lines from the ground states of the studied species)
- The ISM, at -10 km/s. 

In total, the model is described by ~ 100 parameters, and is fitted to the entire observed spectrum (10,000 to 20,000 degrees of freedom).

***

# 2025-04-29 observations

***

```{python}
#| output: false
#| warning: false
# # Prepare the analysis:
#   + Recover the observed data
#   + Identify the fitted lines
#   + Retrieve datasets of spectroscopic data for the studied species, to calculate their excitation states
#   + Retrieve instrumental properties (LSF)

import Settings_2025_04_29_refrac_carbon as Settings

Analysis_dic_2025_04_29 = Routines.Prepare_analysis(Settings.settings)
```

```{python}
# Best-fit model parameters

dic_params_all_components = {

    # First component: exocomet at -7 km/s (LVC 1)
    0: {'d': 0.892,              # Transit distance (in AU, relative to Beta Pic)
        'Delta_d': 0.0,          # Width of the cloud, in AU (in AU, here set to 0)
        'f_esc': 0.175,          # Ratio between the transverse and radial column density of the cloud (between 0 and 1)
        'xi': 0.0,               # Turbulent velocity dispersion of the cloud (in km/s, here set to 0)
        'T_i': 7081.0,           # Ionic temperature (in K)
        'log_n_e': 4.32,         # Logarithm of electronic density (in cm-3)
        'log_T_e': 4.396,        # Logarithm of electronic temperature (in K)
        'v': [-13.57, -11.57, -9.57, -7.436, -5.57, -3.57, -1.57],            # Velocities at from which the component profiles are interpolated (in km/s, fixed during the fit)
        'alpha': [0.956, 0.956, 0.956, 0.956, 0.956, 0.956, 0.956],           # Covering factor profile (here we fit for only one covering factor, assued to be the same for all RV)
        'phi_macro': [0.029, 0.117, 0.444, 1.0, 0.488, 0.0885, 0.044],        # Line profile of the component (max = 1)
          'N': {'Fe II': 3.422,        # Column densities of the studied species (7 refractory species + C I and 13C I)
                'Ni II': 0.239, 
                'Ca II': 0.0172, 
                'Cr II': 0.0263, 
                'Mn II': 0.0175, 
                'Si II': 4.857, 
                'S I': 0.0275, 
                'C I 3P 1/2': 0.475,       # Four lowest states of 12C I 
                'C I 3P 3/2': 1.425, 
                'C I 3P 5/2': 2.375, 
                'C I 1D 5/2': 0.256, 
                '13C I 3P 1/2': 0.0317,    # 13C is assumed to be 1/15 of 12C
                '13C I 3P 3/2': 0.095, 
                '13C I 3P 5/2': 0.158, 
                '13C I 1D 5/2': 0.0171}}, 

    # Second component: exocomet at +2 km/s (LVC 2)
    1: {'d': 4.756, 
        'Delta_d': 0.0, 
        'f_esc': 0.0959, 
        'xi': 0.0, 
        'T_i': 2081.0, 
        'log_n_e': 3.438, 
        'log_T_e': 2.993, 
        'v': [-3.45, -1.45, 0.55, 2.47, 4.55, 6.55, 8.55], 
        'alpha': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 
        'phi_macro': [0.0174, 0.0853, 0.694, 1.0, 0.634, 0.105, 0.00935], 
        'N': {'Fe II': 6.258, 
              'Ni II': 0.315, 
              'Ca II': 0.0721, 
              'Cr II': 0.0723, 
              'Mn II': 0.0311, 
              'Si II': 4.949, 
              'S I': 0.131, 
              'C I 3P 1/2': 1.268, 
              'C I 3P 3/2': 0.933, 
              'C I 3P 5/2': 1.05, 
              'C I 1D 5/2': 0.102, 
              '13C I 3P 1/2': 0.0845, 
              '13C I 3P 3/2': 0.0622, 
              '13C I 3P 5/2': 0.07, 
              '13C I 1D 5/2': 0.0068}}, 

    # Third component: exocomet at +10 km/s (LVC 3)
    2: {'d': 1.72, 
        'Delta_d': 0.0, 
        'f_esc': 0.0516, 
        'xi': 0.0, 
        'T_i': 1846.0, 
        'log_n_e': 3.083, 
        'log_T_e': 3.923, 
        'v': [4.7, 6.4, 8.036, 9.72, 11.2, 13.2, 14.9, 16.6, 18.3], 
        'alpha': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 
        'phi_macro': [0.0274, 0.0463, 0.219, 1.0, 0.243, 0.185, 0.0368, 0.023, 0.0135], 
        'N': {'Fe II': 1.52,
              'Ni II': 0.102, 
              'Ca II': 0.00951, 
              'Cr II': 0.0186, 
              'Mn II': 0.00807, 
              'Si II': 2.175, 
              'S I': 0.0161, 
              'C I 3P 1/2': 0.33, 
              'C I 3P 3/2': 0.94, 
              'C I 3P 5/2': 1.12, 
              'C I 1D 5/2': 0.0594, 
              '13C I 3P 1/2': 0.022, 
              '13C I 3P 3/2': 0.063, 
              '13C I 3P 5/2': 0.075, 
              '13C I 1D 5/2': 0.00396}}, 

    # Fourth component: circumstellar disc at 0 km/s
    3: {'d': 76.16, 
        'Delta_d': 0.0, 
        'f_esc': 0.3, 
        'xi': 1.032, 
        'T_i': 0.0, 
        'log_n_e': 2.184, 
        'log_T_e': 3.073, 
        'v': [0.0], 
        'alpha': [1.0], 
        'phi_macro': [1.0], 
        'N': {'Fe II': 2.0, 
              'Ni II': 0.155, 
              'Ca II': 0.216, 
              'Cr II': 0.0396, 
              'Mn II': 0.0119, 
              'Si II': 1.798, 
              'S I': 0.102, 
              'C I 3P 1/2': 45.64, 
              'C I 3P 3/2': 63.93, 
              'C I 3P 5/2': 30.43, 
              'C I 1D 5/2': 0.0, 
              '13C I 3P 1/2': 3.043, 
              '13C I 3P 3/2': 4.262, 
              '13C I 3P 5/2': 2.029, 
              '13C I 1D 5/2': 0.0}}}



# Meta parameters for each component:
#    + 'n_pix' : number of pixels used to compute the alpha and line profiles
#    + 'd_N_bin' : width (in 10^14 cm-2) of the gas bins used to discretize each component, in order to take their self absorption in the computation of their excitation states. 
#    + 'sp_ref' : reference species for d_N_bin
#    + 'geometry' : either 'cylind' or 'slab', involved in the computation of the escape probability
meta_params = {0: {'n_pix': 7, 'd_N_bin': 0.3, 'sp_ref': 'Fe II', 'geometry': 'cylind'}, 
               1: {'n_pix': 7, 'd_N_bin': 0.3, 'sp_ref': 'Fe II', 'geometry': 'cylind'}, 
               2: {'n_pix': 9, 'd_N_bin': 0.3, 'sp_ref': 'Fe II', 'geometry': 'cylind'}, 
               3: {'n_pix': 1, 'd_N_bin': 0.3, 'sp_ref': 'Fe II', 'geometry': 'slab'}}


# Number of components
n_comp = 4

# Convert dictionnary of parameters into a list (easier for MCMC fitting)
list_params_all_components = Routines.dic_to_list(dic_params_all_components, meta_params, Analysis_dic_2025_04_29['List_species'])
```

```{python}
#| output: false
#| warning: false
# # Compute the model and chi2
dic_params_all_components, line_profiles_all_components, abundances_all_components = Routines.calc_abundances(Analysis_dic_2025_04_29, list_params_all_components, meta_params, n_comp)
transmitted_flux_all_components = Routines.calc_full_profile(Analysis_dic_2025_04_29, abundances_all_components, dic_params_all_components, line_profiles_all_components)
dic_flux_all_orders_2025_04_29 = Routines.resample_model_orders(Analysis_dic_2025_04_29, transmitted_flux_all_components, n_comp, resample_components = True)
chi2,dof = Routines.calc_chi2(dic_flux_all_orders_2025_04_29)

print('Chi2 :', chi2)
print('Reduced Chi2 :', chi2/Analysis_dic_2025_04_29['dof'])
```

### View of full fitted spectrum: 

- Observations are shown in grey;
- The reference spectrum is shown in black;
- Contributions from the three Low-Velocity Exocomets (LVC) are shown in blue (LVC 1), green (LVC 2) and orange (LVC 3);
- Contributions from the disc and the ISM are shown in dashed and dot-dashed, respectively;
- The full model, convolved by the instrumental LSF, is shown in red.

Each fitted line is indicated with a purple tick. The species, excitation level, and oscillator strength can be displayed by hovering over the tick.

```{python}
# Plot full spectrum (STIS + COS + HARPS)
Routines.plot_exocomet_model(Analysis_dic_2025_04_29, dic_flux_all_orders_2025_04_29, n_comp, 
                             plot_model_HR = True, plot_model_LR = False, plot_error_bar = False)
```

### Zoom to two Fe II and C I lines:

```{python}
# View of the Fe II line at 2629 A
Routines.plot_exocomet_model(Analysis_dic_2025_04_29, dic_flux_all_orders_2025_04_29, n_comp, 
                       plot_model_HR = True, plot_model_LR = False, 
                       line = 2629.0766, xlim = [-150,150], plot_error_bar = True)
```

```{python}
# View of the C I line at 1560.3 A

Routines.plot_exocomet_model(Analysis_dic_2025_04_29, dic_flux_all_orders_2025_04_29, n_comp, 
                       plot_model_HR = True, plot_model_LR = False, plot_error_bar = True, 
                       line = 1560.308, xlim = [-150,150], ylim = [0,2e-12])
```

***

# 2025-09-10 observations

***

```{python}
#| output: false
#| warning: false
# # Prepare the analysis
import Settings_2025_09_10_refrac_carbon as Settings

Analysis_dic_2025_09_10 = Routines.Prepare_analysis(Settings.settings)
```

```{python}
# Best fit model parameters

dic_params_all_components = {

    # First component: exocomet at +4 km/s (LVC 4)
    0: {'d': 0.54, 
        'Delta_d': 0.0, 
        'f_esc': 0.182, 
        'xi': 0.0, 
        'T_i': 0.0, 
        'log_n_e': 5.0, 
        'log_T_e': 4.464, 
        'v': [-20.0, -17.0, -14.0, -11.0, -8.0, -5.0, -2.0, 1.0, 7.0, 10.0, 13.0, 16.0, 19.0, 22.0, 25.0, 28.0, 31.0, 34.0, 37.0], 
        'alpha': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.973, 0.957, 0.933, 0.915, 0.801, 0.796, 0.85, 0.612, 0.615, 0.241], 
        'phi_macro': [0.000101, 0.0002, 0.00566, 0.00941, 0.025, 0.0575, 0.129, 0.169, 0.412, 0.59, 1.0, 0.542, 0.217, 0.128, 0.0501, 0.0166, 0.00578, 0.00373, 0.000938], 
        'N': {'Fe II': 11.04, 
              'Ni II': 0.898, 
              'Ca II': 0.0749, 
              'Cr II': 0.108, 
              'Mn II': 0.06, 
              'Si II': 13.89, 
              'S I': 0.0795, 
              'C I 3P 1/2': 1.32, 
              'C I 3P 3/2': 3.96, 
              'C I 3P 5/2': 6.601, 
              'C I 1D 5/2': 0.896, 
              '13C I 3P 1/2': 0.088, 
              '13C I 3P 3/2': 0.264, 
              '13C I 3P 5/2': 0.44, 
              '13C I 1D 5/2': 0.0597}}, 
              
    # Second component: exocomet at +13 km/s (LVC 5)
    1: {'d': 3.82, 
        'Delta_d': 0.0, 
        'f_esc': 0.301, 
        'xi': 0.0, 
        'T_i': 1757.0, 
        'log_n_e': 3.46, 
        'log_T_e': 3.711, 
        'v': [-0.48, 1.02, 2.52, 4.02, 5.52, 7.02, 8.52], 
        'alpha': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 
        'phi_macro': [0.0749, 0.123, 0.493, 1.0, 0.396, 0.149, 0.0752], 
        'N': {'Fe II': 4.485, 
              'Ni II': 0.239, 
              'Ca II': 0.0298, 
              'Cr II': 0.048, 
              'Mn II': 0.0215, 
              'Si II': 3.882, 
              'S I': 0.0377, 
              'C I 3P 1/2': 0.852, 
              'C I 3P 3/2': 2.555, 
              'C I 3P 5/2': 4.258, 
              'C I 1D 5/2': 0.0411, 
              '13C I 3P 1/2': 0.0568, 
              '13C I 3P 3/2': 0.17, 
              '13C I 3P 5/2': 0.284, 
              '13C I 1D 5/2': 0.00274}}, 

    # Third component: small gas cloud at -1 km/s. Not studied in the paper, but adding this component improves a lot the fit in Fe II lines
    2: {'d': 7.641, 
        'Delta_d': 0.0,
          'f_esc': 0.0, 
          'xi': 0.949, 
          'T_i': 0.0, 
          'log_n_e': 0.0, 
          'log_T_e': 4.0, 
          'v': [-1.785], 
          'alpha': [1.0], 
          'phi_macro': [1.0], 
          'N': {'Fe II': 0.247, 
                'Ni II': 0.016, 
                'Ca II': 0.00136, 
                'Cr II': 0.00247, 
                'Mn II': 0.00148, 
                'Si II': 0.247, 
                'S I': 0.00247, 
                'C I 3P 1/2': 0.0411, 
                'C I 3P 3/2': 0.123, 
                'C I 3P 5/2': 0.206, 
                'C I 1D 5/2': 0.0, 
                '13C I 3P 1/2': 0.00274, 
                '13C I 3P 3/2': 0.00822, 
                '13C I 3P 5/2': 0.0137, 
                '13C I 1D 5/2': 0.0}},

    # Fourth component: circumstellar disc at 0 km/s
    3: {'d': 63.43, 
        'Delta_d': 0.0, 
        'f_esc': 0.498, 
        'xi': 0.754, 
        'T_i': 0.0, 
        'log_n_e': 2.2, 
        'log_T_e': 2.303, 
        'v': [0.0], 
        'alpha': [1.0], 
        'phi_macro': [1.0], 
        'N': {'Fe II': 2.46, 
              'Ni II': 0.145, 
              'Ca II': 0.16, 
              'Cr II': 0.0373, 
              'Mn II': 0.0128, 
              'Si II': 1.198, 
              'S I': 0.28, 
              'C I 3P 1/2': 45.64, 
              'C I 3P 3/2': 63.93, 
              'C I 3P 5/2': 30.43, 
              'C I 1D 5/2': 0.0, 
              '13C I 3P 1/2': 3.043, 
              '13C I 3P 3/2': 4.262, 
              '13C I 3P 5/2': 2.029, 
              '13C I 1D 5/2': 0.0}}}




meta_params = {0: {'n_pix': 19, 'sp_ref': 'Fe II', 'd_N_bin': 0.3, 'include_collisions': 'all', 'geometry': 'cylind'}, 
                   1: {'n_pix': 7, 'sp_ref': 'Fe II', 'd_N_bin': 0.3, 'include_collisions': 'all', 'geometry': 'cylind'}, 
                   2: {'n_pix': 1, 'sp_ref': 'Fe II', 'd_N_bin': 10, 'include_collisions': 'all', 'geometry': 'cylind'}, 
                   3: {'n_pix': 1, 'sp_ref': 'Fe II', 'd_N_bin': 0.3, 'include_collisions': 'all', 'geometry': 'slab'}, 'comet': {'n_params_comet': 0}}


n_comp = 4

list_params_all_components = Routines.dic_to_list(dic_params_all_components, meta_params, Analysis_dic_2025_09_10['List_species'])
```

```{python}
#| output: false
#| warning: false
# # Compute the model and chi2

dic_params_all_components, line_profiles_all_components, abundances_all_components = Routines.calc_abundances(Analysis_dic_2025_09_10, list_params_all_components, meta_params, n_comp)
transmitted_flux_all_components = Routines.calc_full_profile(Analysis_dic_2025_09_10, abundances_all_components, dic_params_all_components, line_profiles_all_components)
dic_flux_all_orders_2025_09_10 = Routines.resample_model_orders(Analysis_dic_2025_09_10, transmitted_flux_all_components, n_comp, resample_components = True)
chi2,dof = Routines.calc_chi2(dic_flux_all_orders_2025_09_10)

print('Chi2 :', chi2)
print('Reduced Chi2 :', chi2/Analysis_dic_2025_09_10['dof'])
```

### View of full fitted spectrum: 

- Observations are shown in grey;
- The reference spectrum is shown in black;
- Contributions from the three Low-Velocity Exocomets (LVC) are shown in purple (LVC 4) and cyan (LVC 5);
- Contributions from the disc and the ISM are shown in dashed and dot-dashed, respectively;
- The full model, convolved by the instrumental LSF, is shown in red.

Each fitted line is indicated with a purple tick. The species, excitation level, and oscillator strength can be displayed by hovering over the tick.

```{python}
# Plot full spectrum (STIS + COS + HARPS)

Routines.plot_exocomet_model(Analysis_dic_2025_09_10, dic_flux_all_orders_2025_09_10, n_comp, 
                       plot_model_HR = True, plot_model_LR = False)
```

### Zoom to two Fe II and C I lines:

```{python}
# View of the Fe II line at 2629 A

Routines.plot_exocomet_model(Analysis_dic_2025_09_10, dic_flux_all_orders_2025_09_10, n_comp, 
                       plot_model_HR = True, plot_model_LR = False, plot_error_bar = True, 
                       line = 2629.0766, xlim = [-150,150])
```

```{python}
# View of the C I line at 1560.3 A
Routines.plot_exocomet_model(Analysis_dic_2025_09_10, dic_flux_all_orders_2025_09_10, n_comp, 
                       plot_model_HR = True, plot_model_LR = False, plot_error_bar = True,
                       line = 1560.308, xlim = [-150,150], ylim = [0,2e-12])
```

